### ISSUE TITLE
Can't fetch private UPM Packages from github because can't add my github credentials to Unity

### ISSUE THREAD

**Issue by Podden** [game-ci/unity-builder#161]
**Bug description**
We're using private packages from github in the Unity Package Manager. Building does not work with this because Unity asks for my github credentials. On my local Windows machine, Github Crendetial Manager pops up and I can insert them. What do I have to do in an github action to add them?

```
- stderr: fatal: could not read Username for 'https://github.com': terminal prompts disabled
Project has invalid dependencies:
de.lefx.stepmanager: Error when executing git command. fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

I've tried to add my github credentials with fusion-engineering/setup-git-credentials@v2.0.1 but does not work either.

**How to reproduce**

Try building a project with UPM dependency from a private github URL.

**Expected behavior**

Project builds :)

**Additional details**

I've added my script and the logfiles

[build.zip](https://github.com/webbertakken/unity-builder/files/5378077/build.zip)
[logs_51.zip](https://github.com/webbertakken/unity-builder/files/5378079/logs_51.zip)

**Comment by GabLeRoux** [comment]
I'd say a workaround would be to clone these projects as part of your CI before building them. Related question on Support community:  
https://github.community/t/best-way-to-clone-a-private-repo-during-script-run-of-private-github-action/16116

You'll need a _personal access token_ generated from [here](https://github.com/settings/tokens/new). Check the `Repo` checkbox to access private repository. This token will grant access to what you have access to in terms of private repos.

In your action file, you can add a step like this:

```yaml
- uses: actions/checkout@v1
  with:
    repository: my-private/repo-name
    token: ${{ secrets.ACCESS_TOKEN }}
```

**Comment by TheoRealcast** [comment]
Hi !

I have the exact same need as @Podden. I tried @GabLeRoux  workaround by cloning dependencies directly to Unity's package cache folder but it looks like it's not working.  


Dependencies referenced by the Packages/manifest.json can be written as follow : 

```json
"yourpackagename": "git+ssh://git@github.com/company/yourpackagename.git#tag-or-sha1"
```

This way git doesn't ask for username/password on the command line and will look for your ssh keys instead.
But it doesn't seem to work (relevant log extract below with further investigation). That being said, it could work by using FILE protocol in manifest.json (not tested yet), but it's not very flexible since you would need to update your workflow files each time you need to update your project dependencies...

Here is my log extract when trying with git+ssh in manifest.json
```
COMMAND LINE ARGUMENTS:
/opt/Unity/Editor/Unity
-batchmode
-logfile
/dev/stdout
-quit
-customBuildName
StandaloneWindows64
-projectPath
/github/workspace/.
-buildTarget
StandaloneWindows64
-customBuildTarget
StandaloneWindows64
-customBuildPath
/github/workspace/build/StandaloneWindows64/StandaloneWindows64.exe
-executeMethod
UnityBuilderAction.Builder.BuildProject
-buildVersion
1.1.201
-androidVersionCode
1001201
-androidKeystoreName

-androidKeystorePass

-androidKeyaliasName

-androidKeyaliasPass

-nographics
Successfully changed project path to: /github/workspace/.
/github/workspace
Using Asset Import Pipeline V2.
DisplayProgressbar: Unity Package Manager
Rebuilding Library because the asset database could not be found!
Adding genesis user token Error when executing git command:
  - stdout: 
  - stderr: No user exists for uid 1001
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Error when executing git command:
  - stdout: 
  - stderr: No user exists for uid 1001
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
 
Googling things like 'No user exists for uid 1001' shows that it seems to be related to how docker changes user but I'm not really used to Docker and clean permission handling on linux... I tried (with no luck) adding entries in /etc/passwd as suggested [here](https://github.com/bitnami/bitnami-docker-jenkins/issues/60#issuecomment-708305057)

[Here](https://community.home-assistant.io/t/ssh-under-docker-when-no-user-exists-for-uid/157457) is another link that seems relevant to me , but I really have no idea on how to apply that.

Here is my workflow file : 

```yaml
name: Build App

on:
  push: { branches: [master] }
  workflow_dispatch: { branches: [master] }

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        projectPath:
          - ./
        unityVersion:
          - 2019.4.4f1
        targetPlatform:
          - StandaloneWindows64
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: false

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.PRIVATE_TOKEN }}
            repository: company/mypackage
            ref: 1.0.0
            path: ${{ matrix.projectPath }}/Library/PackageCache/mypackage

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      - name: Create SSH key
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          sudo mkdir -p /home/github/.ssh/
          sudo ssh-keyscan github.com >> /home/github/.ssh/known_hosts
          sudo ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          sudo echo $SSH_PRIVATE_KEY > /home/github/.ssh/private.key
          sudo echo "Host *" > /home/github/.ssh/config
          sudo echo "   IdentityFile /home/github/.ssh/private.key" >> /home/github/.ssh/config
          sudo chown -R runner:runner /home/github/
          sudo chmod 0600 /home/github/.ssh/private.key
        shell: bash

      # Build
      - name: Unity - Builder
        uses: webbertakken/unity-builder@v1.4
        env:
          # Unity Pro Licence Activation
          # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          # UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          # Unity Personal License Activation
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:
          customParameters: -nographics
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
```
