### ISSUE TITLE
Personal License Key not working

### ISSUE THREAD

**Issue by josephdigipen** [game-ci/unity-builder#204]
**Bug description**

Follow Docs:
https://game.ci/docs/github/activation

Generate License Key with yml:
```yaml
name: Acquire activation file

on: [push]
jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v1.2
        with:
          unityVersion: 2020.1.1f1
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
```

Try to build with License in Secrets:
```yaml
name: CI_Test

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ feature/*, hotfix/* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - name: Build Unity Project
        uses: game-ci/unity-builder@main
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 2020.1.1f1
```

Getting License Error:
```
Requesting activation (personal license)
Activation complete.

...

[Licensing::Module] Channel doesn't exist: "LicenseClient-root"
[Licensing::Module] Successfully launched the LicensingClient (PId: 87)
[SignatureVerifier] Application signature verification not supported on this platform.
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-root" (connect: 0.54s, validation: 0.07s, handshake: 0.00s)
[Licensing::Module] Connected to LicensingClient (PId: 87, launch time: 0.00, total connection time: 0.61s)
Entitlement-based licensing initiated
[LicensingClient] Licenses updated successfully

LICENSE SYSTEM [2021125 18:43:40] Next license update check is after 2021-01-26T18:38:41


LICENSE SYSTEM [2021125 18:43:40] Machine binding 1 mismatch: (value of current machine) ********* != ********* (value in license file). Reason might be there is a hardware change on this machine after the license was activated.


LICENSE SYSTEM [2021125 18:43:40] Machine binding 2 mismatch: (value of current machine) ********* != ********* (value in license file). Reason might be there is a hardware change on this machine after the license was activated.


LICENSE SYSTEM [2021125 18:43:40] Machine identification is invalid for current license.
DisplayProgressbar: Unity license
Current license is invalid and cannot be activated. You must delete the license file and then activate a new license on current machine. 
(Filename: ./Platforms/Linux/Modules/LicensingLegacy/LinuxILicensingAdapter.cpp Line: 101)
```

**Expected behavior**

Build Correctly
