### ISSUE TITLE
Android signing is not working

### ISSUE THREAD

**Issue by dopaminegamesstudio** [game-ci/unity-builder#209]
**Bug description**

When I add `androidKeystoreName`, It seems that the android build is not using that and use some other keys for signing  (The custom key store is not ticked in unity editor as the document said) 

Error after uploading to google play : 

```
[!] Google Api Error: forbidden: The Android App Bundle was signed with the wrong key. Found: SHA1: 
22:59:3D:65:70:BB:95:44:31:BB:F2:F4:7F:29:B4:4B:B4:60:5C:5A, expected: SHA1: 
E9:61:CD:E5:51:BF:84:CE:D0:2B:64:B3:36:CE:EE:B0:46:78:D6:64. - The Android App Bundle was signed with the wrong key. Found: 
SHA1: 22:59:3D:65:70:BB:95:44:31:BB:F2:F4:7F:29:B4:4B:B4:60:5C:5A, expected: SHA1: 
E9:61:CD:E5:51:BF:84:CE:D0:2B:64:B3:36:CE:EE:B0:46:78:D6:64.
```

I even add some wrong base64 input to see what will happen and here is some part of the logs : 

``` 
2021-02-02T20:24:06.3590246Z -rw-r--r-- 1 root root   86 Feb  2 20:24 VersionGenerator.cs.meta
2021-02-02T20:24:06.3594996Z base64: invalid input
2021-02-02T20:24:06.3596071Z Created Android keystore.
2021-02-02T20:24:06.3597502Z Using custom parameters .
```
But even with that error, the project successfully builds with no signing error.

This is my github action:

```
on:
  push: { branches: [ release,feature/cicd ] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildForAndroidPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2020.2.2f1
        targetPlatform:
          #          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
      - uses: webbertakken/unity-builder@v2.0-alpha-6
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          androidAppBundle: true
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
```
