### ISSUE TITLE
WebGL builds have no audio

### ISSUE THREAD

**Issue by AmoghSubhedar** [game-ci/unity-builder#223]
**Bug description**

When building my project on version 2019.4.10f1, the final WebGL build does not play any audio.
Can also see some NULL reference exceptions in the browser console when PlayOneShot was called.
The audio works when built locally on windows 10.

**How to reproduce**

-  Using the code snippet below to create a WebGL build.
-  Hosting the build through github pages
- Testing the build and hearing no audio

`     - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          allowDirtyBuild: true
          projectPath: Phong/
          unityVersion: 2019.4.10f1
          targetPlatform: WebGL
          buildsPath: .
          buildName: WebBuild
`

**Expected behavior**

Audio should play in main menu on awake as well as in-game.

**Additional details**

I did also try Unity versions 2019.3.8f1 and 2019.4.12f1 as well as ubuntu-18.04 and 16.04

Similar issue found on Unity's issue tracker (has been resolved): https://issuetracker.unity3d.com/issues/audio-no-longer-plays-in-build

Another thread with a similar description: https://forum.unity.com/threads/no-sound-clips-in-webgl-build.1016086/

Null reference exceptions:
![image](https://user-images.githubusercontent.com/16474037/109542265-b1f22500-7a79-11eb-9609-ccda5ba10f23.png)

**Comment by johanhelsing** [comment]
Hi, I have the same issue with 2020.2.3 (after the resolved issue linked above is supposed to be fixed) and unityci image version 0.9.

**Comment by zmays** [comment]
Personally I had to make my own dockerfile to get audio to work:

```
FROM unityci/editor:ubuntu-2020.1.13f1-webgl-0.10.0

RUN apt-get update && apt-get install ffmpeg -y
```

You can reference your own dockerfile in the action yml:

```
      - name: build
        id: build
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          customImage: 'zmays/unity-editor:latest'
```
