### ISSUE TITLE
 Artifacts cannot find the build folder 

### ISSUE THREAD

**Issue by fabriciohod** [game-ci/unity-builder#224]
**Artifact upload cannot find the build folder, probably i doing some wrong but i don't found the error**
![](https://i.imgur.com/7Fj0d3E.png)
```yml
name: Actions 😎

on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        buildName:
          - testCi
        projectPath:
          - NewUnityProject
        unityVersion:
          - 2020.2.6f1
        targetPlatform:
#          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
#          - StandaloneLinux64 # Build a Linux 64-bit standalone.
#          - iOS # Build an iOS player.
#          - Android # Build an Android player.
#          - WebGL # WebGL.
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      # Build
      - name: Build project
        id: myBuildStep
        uses: game-ci/unity-builder@v2
        with:
          buildsPath: ${{ github.workspace }}/Builds/
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: ${{ github.workspace }}/Builds/${{ matrix.targetPlatform }}
```

**Comment by webbertakken** [comment]
Not sure why you're adding the github workspace in buildPath and in upload-artifact path.

Recommend simplifying. See https://game.ci/docs/github/builder#complete-example.

**Comment by fabriciohod** [comment]
> Not sure why you're adding the github workspace in buildPath and in upload-artifact path.
> 
> Recommend simplifying. See https://game.ci/docs/github/builder#complete-example.

I'm using github workspace to go to the root of the repository, I tried to use it as it was in the documentation but it gave the same error

**Comment by davidmfinol** [comment]
If you search for `customBuildPath` in your logs, does it match '/home/runner/work/testCi/testCi/Builds/StandaloneWindows64'?

**Comment by fabriciohod** [comment]
I didn't find ```custom Build Path``` but the i found this path
![](https://i.imgur.com/QkBJi07.png)
![](https://i.imgur.com/uX1BW1n.png)

**Comment by webbertakken** [comment]
Could you remove the trailing slash in your workflow:

```diff
        with:
-         buildsPath: ${{ github.workspace }}/Builds/
+         buildsPath: Builds
```

and in the upload part:

```diff
      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
-         path: ${{ github.workspace }}/Builds/${{ matrix.targetPlatform }}
+         path: Builds/${{ matrix.targetPlatform }}
```

It should work.

**Comment by fabriciohod** [comment]
Same thing, could not find the folder. I left the public [repository](https://github.com/fabriciohod/testCi) now it could be that I'm taking the folder the wrong way
![](https://i.imgur.com/gbX8lls.png)

**Comment by webbertakken** [comment]
Looks like you also forgot to set https://game.ci/docs/github/builder#projectpath

Which is important because your project is not in the root of your repository.

**Comment by fabriciohod** [comment]
even with `` project path``, I couldn't get it to work
![](https://i.imgur.com/KYt7axv.png)
![](https://i.imgur.com/WtEeOFi.png)
```yml
# Build
      - name: Build project
        id: myBuildStep
        uses: game-ci/unity-builder@v2
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: builds/${{ matrix.targetPlatform }}
```
