### ISSUE TITLE
Error: Branch is dirty. Refusing to base semantic version on uncommitted changes

### ISSUE THREAD

**Issue by montao** [game-ci/unity-builder#241]
I have the same unity version number in my project and in the action yaml file (after guessing how to write it). I could build a WebGL release from the pipeline at first, now I want to build a PC-Windows10 version. It is difficult to understand what is meant by "uncommitted changes". I'm trying to guess what that means. I did not commit anything at all. So something else changed.

_Dirty means that you have made changes after you have ran the checkout job._

I keep guessing what that means I should do. Here's my action
```

#- name: Unity - Builder
#  uses: game-ci/unity-builder@v2.0-alpha-6
name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          # - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          # - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          #- StandaloneLinux64 # Build a Linux 64-bit standalone.
          # - iOS # Build an iOS player.
          # - Android # Build an Android .apk standalone app.
          #- WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 2020.3.2f1
          allowDirtyBuild: true
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

```

**Comment by montao** [comment]
Ok I got it to work by commenting out the cache part... Now my game is built and appears in artifact and I can download and run it. Very cool @webbertakken  !

**Comment by ckcollab** [comment]
For anyone else experiencing this, I had to add `allowDirtyBuild` _(which you have here!?)_ and it "just works:"

```
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 2020.3.2f1
          # adding allowDirtyBuild here fixed it for me!
          allowDirtyBuild: true
```

**Comment by webbertakken** [comment]
@ckcollab The error is there for a reason and simply working around it is not the recommended approach.

If you working directory has changes since you've checked out your branch, this error will show up. The reason for the error and failure is to prevent possible misconfigurations in your workflow. Misconfiguration can potentially lead to bugs in your builds. 

The error also indicates which files are "dirty".

If you're running test-runner in the same workflow, be sure to add `/artifacts`. to your `.gitignore` file.

**Comment by mikkergimenez** [comment]
I'm getting this error on a bunch of files in my assets folder:

```M Assets/Lean/Common/Examples/Meshes/RoundedCube.obj
 M Assets/Lean/Common/Examples/Textures/Description.png
 M Assets/Lean/Common/Examples/Textures/Grid.png
 M Assets/Lean/Common/Examples/Textures/Heart.png
 M Assets/Lean/Common/Examples/Textures/Left.png
 M Assets/Lean/Common/Examples/Textures/Right.png
 M Assets/Lean/GUI/Examples/Media/AlertA.png
 M Assets/Lean/GUI/Examples/Media/AlertB.png
 M Assets/Lean/GUI/Examples/Media/Back.wav
 M Assets/Lean/GUI/Examples/Media/Click.wav
 M Assets/Lean/GUI/Examples/Media/Round10.png
 M Assets/Lean/GUI/Examples/Media/Round10_Blur10.png
 M Assets/Lean/GUI/Examples/Media/Round10_Thickness5.png
 M Assets/Lean/GUI/Examples/Media/Round3.png
 M Assets/Lean/GUI/Examples/Media/Round30.png
 M Assets/Lean/GUI/Examples/Media/Round5.png
 M Assets/Lean/GUI/Examples/Media/Round50.png
 M Assets/Lean/GUI/Examples/Media/Round50_Thickness5.png
 M Assets/Lean/GUI/Examples/Media/Round5_Thickness2.png
 M Assets/Lean/GUI/Examples/Media/Thud.wav
 M "Assets/Sprites/3-Round50 copy.png"
 M Assets/Sprites/3-Round50.png
 M Assets/Sprites/3-Round50.pxd/QuickLook/Icon.tiff
 M Assets/Sprites/3-Round50.pxd/QuickLook/Thumbnail.tiff
 M Assets/Sprites/Round30.png
 M Assets/Sprites/Round50.png
 M Assets/Sprites/antiFlash-icons-gear.svg
 M "Assets/Sprites/top-2-Round50 .png"
 M "Assets/Sprites/top-2-Round50 .pxd/QuickLook/Icon.tiff"
 M "Assets/Sprites/top-2-Round50 .pxd/QuickLook/Thumbnail.tiff"
 M "Assets/TextMesh Pro/Documentation/TextMesh Pro User Guide 2016.pdf"
 M "Assets/TextMesh Pro/Fonts/LiberationSans.ttf"
 M "Assets/TextMesh Pro/Resources/Fonts & Materials/Square.png"
 M "Assets/TextMesh Pro/Sprites/EmojiOne.png"
 M Assets/Tree_Textures/diffuse.png
 M Assets/Tree_Textures/normal_specular.png
 M Assets/Tree_Textures/shadow.png
 M Assets/Tree_Textures/translucency_gloss.png```

I assume this is because the build process tries to install asset packages here?  But I can't find any documentation or further details as to why these assets would be dirty.  Any advice?

**Comment by webbertakken** [comment]
> I'm getting this error on a bunch of files in my assets folder
>
> I assume this is because the build process tries to install asset packages here?  But I can't find any documentation or further details as to why these assets would be dirty.  Any advice?

Don't worry, your assets are very clean 😉 just kidding.

It's the checked out branch that we call dirty when files change after checkout (thus differ from your branch in version control).

1 of two things happened:
1. You checked out without LFS but your files are stored in LFS
1. One of the steps in your workflow actually changed all those files in some way.

In case of 1, be sure to checkout all your files. For example

```yaml
- uses: actions/checkout@v2
  with:
     lfs: true
```

In case of 2, this is not good practice and that's exactly why we're showing throwing an error for it.
