### ISSUE TITLE
The type or namespace name 'dataPath' does not exist

### ISSUE THREAD

**Issue by allnnde** [game-ci/unity-builder#243]
Sorry if my English is not good

When running the builder, it ended up giving me the following error

my project has 4 assambly defined Application, Infrastrucubre, Domain, Presentation with its own .asmdef

```
-----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp-Editor.dll
Microsoft (R) Visual C# Compiler version 3.5.0-dev-20359-01 (8da8ba0c)
Copyright (C) Microsoft Corporation. All rights reserved.

Assets/Editor/Editor/Versioning/Git.cs(107,35): error CS0234: The type or namespace name 'dataPath' does not exist in the namespace 'Application' (are you missing an assembly reference?)
-----EndCompilerOutput---------------
- Finished script compilation in 56.329191 seconds
Assets/Editor/Editor/Versioning/Git.cs(107,35): error CS0234: The type or namespace name 'dataPath' does not exist in the namespace 'Application' (are you missing an assembly reference?)

AssetDatabase: script compilation time: 57.937374s
Scripts have compiler errors.


Aborting batchmode due to failure:
Scripts have compiler errors.

AcceleratorClientConnectionCallback - disconnected - :0
/home/bokken/buildslave/unity/build/PlatformDependent/Linux/External/baselib/builds/Include/C/Baselib_ThreadLocalStorage.inl.h(13): Assertion failed (rc == 0)
Caught fatal signal - signo:5 code:128 errno:0 addr:(nil)
Build failed, with exit code 1
```
my  .yaml
```
name: Deploy

on: [push]

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true
          versioning: None          

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

```

[logs_12.zip](https://github.com/game-ci/unity-builder/files/6300846/logs_12.zip)
