### ISSUE TITLE
Allow spaces in customParameters as parameter

### ISSUE THREAD

**Issue by Philipp-M** [game-ci/unity-builder#244]
AFAIK it is not possible to allow spaces for a parameter
I tried something like the following:
```yaml
customParameters: -productName \"My App\"
customParameters: -productName "My App"
customParameters: -productName \'My App\'
customParameters: -productName 'My App'
```

But inside the unity build script `My App` gets split into two parameters (if `\"` is used, the `"` is added to the parameter.
Is it somehow possible to allow spaces for a parameter?
