### ISSUE TITLE
Files don't get `chown`ed if the action is canceled

### ISSUE THREAD

**Issue by Bradshaw** [game-ci/unity-builder#255]
**Bug description**

If the build is cancelled, the final `chownFilesTo` step doesn't take place, causing the root-owned files to stay root-owned regardless of the option.

**How to reproduce**

- Use the `chownFilesTo` option
- Start a build
- After unity-builder has began building the project, cancel the build

**Expected behavior**

- The files should nevertheless be `chown`ed

**Additional details**

- Proposed solution: Move the `chownFilesTo` step to a "post" step

*e.g:*
```yml
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/chown.js`  👈 Make this
```
