### ISSUE TITLE
Move Build Script to a UPM Package

### ISSUE THREAD

**Issue by davidmfinol** [game-ci/unity-builder#257]
**Context**

Users currently have to redo a lot of the default Build Script if they want to have a custom `buildMethod`.
We should make it easier for users to add to or modify the build method, while still leveraging the default functionality.

**Suggested solution**

Remove the `buildMethod` option, and move the default build script to a UPM package that users could choose to include in their project. 
If they include the UPM package, they should be able to use an API to easily add to or modify the build process.
If they don't include the package, Unity Builder would still work by importing the package during the build action.

**Considered alternatives**

My initial solution was to provide an example `BuildScript.cs` that users could copy and modify, but this approach is still not as user-friendly as it should be.

**Additional details**

This issue came from user feedback:
https://discord.com/channels/710946343828455455/710946344264794219/839682505434595370
https://discord.com/channels/710946343828455455/710946344264794219/839765128564178966

**Comment by Bradshaw** [comment]
Maybe another solution would be to add an option to customise the path to copy UnityBuilderAction from.

https://github.com/game-ci/unity-builder/blob/main/dist/steps/build.sh#L51

So an option like:
```yaml
- uses: game-ci/unity-builder@v2
  env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  with:
    targetPlatform: WebGL
    buildActionPath: /github/workspace/MyCustomBuildAction/
```

And then in `build.sh`:
```bash
cp -R $UNITY_BUILD_ACTION_PATH "$UNITY_PROJECT_PATH/Assets/Editor/"
```

With the necessary plumbing to have `/UnityBuilderAction/Assets/Editor/` as a default value and pass it around of course
