### ISSUE TITLE
Missing read permissions for linux-il2cpp builds

### ISSUE THREAD

**Issue by webbertakken** [game-ci/unity-builder#258]
**Bug description**

Currently all files are owned by root, which does not seem to cause any problem. 
However group read is disabled for build target `linux-il2cpp` (default linux target for 2020.x+), whereas group read access is enabled as expected on other target platforms like `iOS` and `Windows64`.

**How to reproduce**

```yml
name: Build 🛠

on:
  workflow_dispatch: {}
  pull_request: {}
  push: { branches: [main, develop] }

jobs:
  tests:
    name: ${{ matrix.targetPlatform }} 🚀
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Build-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-Build-
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: Build (${{ matrix.targetPlatform }})
          path: build/${{ matrix.targetPlatform }}
```

See [my unity reference project](https://github.com/webbertakken/unity-reference-project).

**Expected behavior**

Read permissions would simply be set.

**Additional details**

Windows (successful)

![image](https://user-images.githubusercontent.com/20756439/117580653-48396b80-b0f9-11eb-8c1b-cd2a92e754c2.png)

Linux IL2CPP (failed to upload)

![image](https://user-images.githubusercontent.com/20756439/117580701-7c149100-b0f9-11eb-9750-ba9fc7149608.png)
