### ISSUE TITLE
Images are not working in the build with pro license and getting white screen everywhere

### ISSUE THREAD

**Issue by KiranI-Bsw** [game-ci/unity-builder#279]
**Bug description**

Recently problem starting to occur, while building with personal license all things are working properly. However, when I use pro license to make build for release it just doesn't show images and everything is white. Build configuration for build with personal license and pro license are exactly the same, just different licensing method. Build type is IL2CPP, using unity builder tag `v2` and unity version `2019.4.10f`. I've slightly modified default build script to change some configuration from build flavor.

**How to reproduce**
```
    - name: Build Unity Project
      id: build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        # UNITY_LICENSE: ${{ secrets.UNITY_PERSONAL_LICENSE }}
      with:
        unityVersion: ${{ env.UNITY_VERSION }}
        targetPlatform: Android
        versioning: None
        buildMethod: UnityBuilderAction.Builder.BuildProject
        buildName: ${{ format('SignedProduction_{0}', env.ANDROID_VERSION_CODE) }}
        androidVersionCode: ${{ env.ANDROID_VERSION_CODE }}
        androidAppBundle: false
        androidKeystoreName: App.keystore
        androidKeystoreBase64: ${{ secrets.ANDROID_SIGN_BASE64 }}
        androidKeystorePass: ${{ secrets.ANDROID_SIGN_PASS }}
        androidKeyaliasName: ${{ secrets.ANDROID_SIGN_ALIAS }}
        androidKeyaliasPass: ${{ secrets.ANDROID_SIGN_ALIAS_PASS }}
        customParameters: '-flavor Production'
```

-

**Expected behavior**

Builds with pro license should also work the same as it is working with personal license.

**Additional details**

- I was using the same code in the past and it worked perfectly untill last week. It is strange that it is working well with personal license. I didn't find anything other that can break the build.
