### ISSUE TITLE
Project with Addressables output location

### ISSUE THREAD

**Issue by zmays** [game-ci/unity-builder#280]
I have a project that uses addressables, but I am having a hard time finding the bundle/assets during ci/cd.

I see this code here:
```
 // Execute default AddressableAsset content build, if the package is installed.
      // Version defines would be the best solution here, but Unity 2018 doesn't support that,
      // so we fall back to using reflection instead.
      var addressableAssetSettingsType = Type.GetType(
        "UnityEditor.AddressableAssets.Settings.AddressableAssetSettings,Unity.Addressables.Editor");
      if (addressableAssetSettingsType != null)
      {
        // ReSharper disable once PossibleNullReferenceException, used from try-catch
        try
        {
          addressableAssetSettingsType.GetMethod("CleanPlayerContent", BindingFlags.Static | BindingFlags.Public)
                .Invoke(null, new object[] {null});
          addressableAssetSettingsType.GetMethod("BuildPlayerContent", new Type[0]).Invoke(null, new object[0]);
        }
        catch (Exception e)
        {
          Debug.LogError($"Failed to run default addressables build:\n{e}");
        }
      }
```

And based on that my assumption is that if I have the addressables package installed it will use my default profile and build the assets (which for my profile should go to ServerData/WebGL), but after the build here is all I have:

<img width="296" alt="Screen Shot 2021-07-28 at 5 07 02 PM" src="https://user-images.githubusercontent.com/4370615/127402468-56f1737c-81b3-46f5-a9b9-13ea4e2507df.png">

build folder being my set build folder, which contains just the regular build assets:

<img width="398" alt="Screen Shot 2021-07-28 at 5 08 13 PM" src="https://user-images.githubusercontent.com/4370615/127402548-fb4d46e2-b234-497a-ac85-1405554b90f1.png">

here is my relevant build piece of my yaml:

```
      - name: build
        id: build
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          buildsPath: build
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
```

Just wanting to confirm my assumptions that I should be getting a ServerData folder build at the root of my project - happy to update docs or chase down further if their isn't something obvious I'm missing.
