### ISSUE TITLE
Error while compiling Unity or something

### ISSUE THREAD

**Issue by Unity123** [game-ci/unity-builder#284]
**Bug description**

When I try and run it, it crashes with this exception:
`Assets/Plugins/GitHub/Editor/UnityAPIWrapper.cs(15,17): error CS0103: The name 'UnityShim' does not exist in the current context`

**How to reproduce**

Run this workflow on a Unity project
```
name: Nightly Build
on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 * * *'

jobs:
  unity_builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0-alpha-11
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows
          unityVersion: 2021.1.17f1
      - name: Automatic Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Nightly Build"
          files: |
            *
```

-

**Expected behavior**

For a release of a build of the source to appear.

**Additional details**

Nothing of note.
