### ISSUE TITLE
Unity Pro license ? Build issue

### ISSUE THREAD

**Issue by YannGROS** [game-ci/unity-builder#288]
Hey guys ! 
I'm new to CI/CD, and I was trying to figure out how to set up all of this with Unity.

Here's my yml file :
```yaml
name: Build Unity Project

on: [push, pull_request, workflow_dispatch]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - NameOfMyProjectFolderWhereMyUnityProjectIs
        unityVersion:
          - 2019.4.5f1
        targetPlatform:
          - StandaloneWindows64 # Build a Windows64 standalone.
          - WebGL # WebGL.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Cache
        uses: actions/cache@v2
        with:  
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          
      - name: Upload          
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
          path: build/${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
```

My unity project is in a subfolder, this is why I've got a projectPath.

I always have an issue at the build step and I can't get rid of it.

I tried several things :
- changing unity password to avoid special characters
- Unity - Activate (I read somewhere that with the pro version it's not necessary)
- using the UNITY_LICENSE like personnal license

Nothing is working, I think some help would be useful !

(The log for the above : [logs_15.zip](https://github.com/game-ci/unity-builder/files/7116788/logs_15.zip), and I also had the "License activation strategy could not be determined.")
