### ISSUE TITLE
Can't Pass ANDROID_KEYSTORE_PASS To Unity Builder Script

### ISSUE THREAD

**Issue by danielginovker** [game-ci/unity-builder#290]
**Bug description**

No matter what I try, I'm unable to pass `ANDROID_KEYSTORE_PASS` to my Unity builder script.

**How to reproduce**

See the following config & code:

`.github/workflows/main.yml`:
```
     - uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
```

`Assets/Editor/AndroidBuilder.cs`:
```
public class AndroidBuilder
{
    static void ProductionBuild()
    {
        foreach(DictionaryEntry e in System.Environment.GetEnvironmentVariables())
        {
            Debug.LogError("Env: " + e.Key  + ":" + e.Value);
        }
        
        string[] scenes = EditorBuildSettings.scenes.Where(scene => scene.enabled).Select(s => s.path).ToArray();
        var buildPlayerOptions = new BuildPlayerOptions
        {
            scenes = scenes,
            target = BuildTarget.Android,
            locationPathName = "build/Build.apk",
        };

        BuildPipeline.BuildPlayer(buildPlayerOptions);
    }
} 
 

```

Output spits out a bunch of environment variables, notably:

> Env: UNITY_EMAIL:***
> Env: UNITY_PASSWORD:***
> Env: UNITY_SERIAL:***
> **Env: ANDROID_KEYSTORE_BASE64:**
> **Env: ANDROID_KEYSTORE_PASS:**
> **Env: ANDROID_KEYALIAS_NAME:**
> **Env: ANDROID_KEYALIAS_PASS:**

(Notice the 4 bottom ones are empty)

The final APK isn't produced and has the error message:

```
UnityException: Can not sign the application
Unable to sign the application; please provide passwords!
```

**Expected behavior**

ANDROID_KEYSTORE_PASS is populated so an APK can be signed

**Additional details**

I've tried so many things. Notably, manually setting the password in AndroidBuilder.cs 

```
        PlayerSettings.keystorePass = "Password123";
```

Builds the APK no problem, indicating the rest of my code works. Any suggestions?

**Comment by danielginovker** [comment]
Also interestingly, when the builder runs it has the envs populated. It's just not working when the actual build occurs, unlike the UNITY_* fields (which are working, as seen by the output above):

![image](https://user-images.githubusercontent.com/76956873/132900672-cc6f63f4-39af-4d72-9bdc-1a7c9510a726.png)

**Comment by webbertakken** [comment]
Looks like `env` in your workflow is not correctly indented.

**Comment by webbertakken** [comment]
Also note that these are not [documented](https://game.ci/docs/github/builder#androidkeystorename) to be passed through `env` at all. You should be using `with` instead.

Try talking to the public API of unity builder, rather than trying to think about the CLI directly. We're trying to have builder be as simple as possible for everyone (including beginning developers).

**Comment by danielginovker** [comment]
Ok so @webbertakken first thank you very much for Game-ci and everything you do ❤️. I've been working on this tirelessly and completely mixed up env / with.

However, it still did not work until I _disabled_ the Custom Keystore as seen here: 
![image](https://user-images.githubusercontent.com/76956873/132922707-169ed4f9-3c5e-4d3f-9b29-fffeb9ba8f5a.png)

Which does not make sense in the docs (I do have a custom keystore name): 
![image](https://user-images.githubusercontent.com/76956873/132922732-cd509559-aa7e-493a-81ee-f6e48bd3ae6c.png)

Although my build now works, I'm not confident enough to say the docs were wrong and submit a PR switching "enable Custom Keystore" to "disable Custom Keystore". Do you have any idea what could have gone wrong here?

Thanks

**Comment by davidmfinol** [comment]
If you disable Custom Keystore, then it should sign with the default keystore.
Are you sure your app isn't being signed with the default keystore now?

Also, are you sure you correctly base64-encoded ANDROID_KEYSTORE_BASE64 in your GitHub Secrets?

**Comment by lebek** [comment]
I had similar issues to @danielginovker above and the fix was to explicitly pass `secrets` from the parent job (by default secrets are not shared and it fails silently).

```yml
jobs:
  call-build-android:
    name: Android
    uses: ./.github/workflows/build-android.yml
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
      ANDROID_KEYALIAS_NAME: ${{ secrets.ANDROID_KEYALIAS_NAME }}
      ANDROID_KEYALIAS_PASS: ${{ secrets.ANDROID_KEYALIAS_PASS }}
```
