### ISSUE TITLE
Location specified by ndk.dir (/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/NDK) did not contain a valid NDK and couldn't be used

### ISSUE THREAD

**Issue by danyow** [game-ci/unity-builder#300]
the action log

```log
FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/Coolest/Coolest/build/Android/Android/Android.apk/unityLibrary/build.gradle' line: 125

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> Location specified by ndk.dir (/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/NDK) did not contain a valid NDK and couldn't be used

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

my action yml file
```yml
name: GameCI Template 🎮

on: push

jobs:

  buildAndroidProject:
    name: Build for Android Project 📱
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          token: ${{ secrets.SUBMODULE }}
          submodules: 'recursive'

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard  

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-Android
          restore-keys: |
            Library-build-
            Library-

      - name: Restore build cache
        uses: actions/cache@v2
        with:
          path: build
          key: Platform-build-Android
          restore-keys: |
            Platform-build-
            Platform-

      - name: Builder
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          chownFilesTo: build/Android 
          targetPlatform: Android
          buildsPath: build/Android
          androidKeystorePass: coolest
          androidKeyaliasName: coolest
          androidKeyaliasPass: coolest
          buildMethod: UnityBuilderAction.BuildScript.Build

      - name: Gradle assembleReleaseChannels
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
          wrapper-cache-enabled: false
          build-root-directory: build/Android/Android/Android.apk
          gradle-version: 6.7.1
          arguments: assembleReleaseChannels
```

> Export Android project but the gradle task didn't work!
