### ISSUE TITLE
Pass env variables to Unity build environment

### ISSUE THREAD

**Issue by Finkes** [game-ci/unity-builder#304]
**Context**

I would like to build multiple flavors of mobile apps (Android & iOS) using GameCI. Therefore during the build I need to modify certain parameters (like the app name, bundle identifier, icon paths, ... ). I tried to pass this information via environment variables. However it seems that since the build is executed inside a Docker container, the environment variables are not present during build time. 

**Suggested solution**

Unless there is another option to pass my own parameters into the build, it would be great to forward all available env variables to the docker build container.

**Considered alternatives**

- customParameters (seem to have a different use case which is special build parameters?)

**Additional details**

Example workflow in GitHub Actions:
```yaml
      - uses: game-ci/unity-builder@v2
        env:
          APP_NAME: ${{ matrix.appName }}
          APP_PACKAGE_NAME: ${{ matrix.packageName }}
          APP_ICON_PATH: ${{ matrix.appIconPath }}
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          androidAppBundle: true
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
```

And this is how I would like to react to this parameter during the Unit Build, using a Prebuild script:
```cs 
public class PreBuild : IPreprocessBuildWithReport
{
    public int callbackOrder { get { return 0; } }

    public void OnPreprocessBuild(BuildReport report)
    {
        Debug.Log("Executing PreBuild script");

        // read parameter from environment variables. Use a fallback if empty
        var appID = this.getEnv("APP_PACKAGE_NAME", "default.package.name");
       
       // use the parameter to modify some player settings like the bundleID
       PlayerSettings.applicationIdentifier = appID;
   }
}
```

**Comment by Finkes** [comment]
After reading [this](https://stackoverflow.com/questions/40229182/simplest-way-of-passing-all-host-environment-variables-to-docker-container) I think for safety reasons we could also come up with a special prefix (like `X_GAMECI_` or `X_UNITY_`) to better control which parameters exactly are being passed into the docker container.

**Comment by davidmfinol** [comment]
You can already do this using a combination of `buildMethod` and `customParameters`. For example, you could have `customParameters: myCustomAppId my.app.id` and then use `PlayerSettings.applicationIdentifier = options["customAppId"];` in the [buildMethod](https://game.ci/docs/github/builder#buildmethod)

**Comment by Finkes** [comment]
@davidmfinol thanks a lot for your quick support! Yes that works for me. I was a bit confused since those parameters are added to the unity binary as command line args. I didn't expect that to work for custom params but it seems that Unity simply ignores any self invented additional parameters in this case.

In addition I also found an option without the need to modify the default build script, so here a quick summary for the records in case someone is interested:
1. As explained by @davidmfinol we can use our own buildMethod based on the code of the default buildMethod as explained [here](https://game.ci/docs/github/builder#buildmethod).
2. Since I wanted to re-use the default build script without the need to modify it if possible, the snippet below is what I came up with. It also reads the `CUSTOM_PARAMETERS` env variable directly inside another build script which is executed in addition to the default build script. I prefer using a separate script since that way I can benefit of any possible new features / improvements / bug fixes in the default build script.

```cs
public class PreBuild : IPreprocessBuildWithReport
{
    public int callbackOrder { get { return 0; } }

    private Dictionary<string,string> customParameters = new Dictionary<string, string>(); 

    public void OnPreprocessBuild(BuildReport report)
    {
        Debug.Log("Executing PreBuild script");
        parseCustomParameters();
        var appID = this.getCustomParam("appId", "de.dfinkbeiner.blockwise.beta");
        var appName = this.getCustomParam("appName", "blockwise (local)");
        var appIconPath = this.getCustomParam("appIconPath", "local"); // can be live, beta or local
    }

    private void parseCustomParameters(){
        var customParamsString = Environment.GetEnvironmentVariable("CUSTOM_PARAMETERS");
        Debug.Log("CUSTOM_PARAMETERS: " + customParamsString);
        if(customParamsString != null){
            var customParams = customParamsString.Split(' ');
            foreach(var customParam in customParams){
                var keyValuePair = customParam.Substring(1).Split('=');
                customParameters.Add(keyValuePair[0], keyValuePair[1]); 
            }
        }
    }

    private string getCustomParam(string key, string defaultValue){
        var customValue = customParameters[key];
        if (customValue != null){
            Debug.Log("Load value from customParams: " + key + "=" + customValue);
            return customValue;
        }
        return defaultValue;
    }
``` 

Workflow File:
```yaml
      - uses: game-ci/unity-builder@v2
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          androidAppBundle: true
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          customParameters: -appId=${{ matrix.packageName }} -appName=${{ matrix.appName }} -appIconPath=${{ matrix.appIconPath }}

```
