### ISSUE TITLE
importing a package before building

### ISSUE THREAD

**Issue by megetron** [game-ci/unity-builder#313]
what i'm trying to achieve is the ability to import external package before building the unity project.

tried to do this (without sucess):
```
      - name: Import SDK
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customParameters: -quit -batchmode -importPackage mypackage.unitypackage
```

can one get the unity executable path to run some unity commands such as:
```
      - name: Import SDK
        run: /opt/unity/Editor/Unity -importPackage mypackage.unitypackage
```
