### ISSUE TITLE
Creating a build of StandaloneOSX it doesn't work on Mac with M1 chip

### ISSUE THREAD

**Issue by danitseitlin** [game-ci/unity-builder#329]
**Bug description**
When creating a build of StandaloneOSX it doesn't work on Mac with M1 chip

**How to reproduce**
build a StandaloneOSX and try to run on Macbook with M1 chip

**Expected behavior*:
The game starts

**Additional details**

**Comment by webbertakken** [comment]
Could you please be slightly more descriptive? Are you building on a Mac runner with M1 chip or are you trying to execute the resulting artifact after a successful build on a Mac with M1? 

Can you speak for whether your other builds work etc.?

**Comment by danitseitlin** [comment]
@webbertakken I am trying to run the artifact on a Macbook with M1 Chip.
I am getting this:
<img width="262" alt="Screen Shot 2022-01-30 at 22 13 03" src="https://user-images.githubusercontent.com/39850374/151715996-3fe2facc-0497-4ba1-a38f-6f6b9104b583.png">
Other builds for Windows64bit works.

**Comment by davidmfinol** [comment]
Does it work on an intel mac? 
Have you tried `chmod +x` to confirm it isn't a permissions issue? 
Are you able to get it to work with a simple project that only has a small sample scene in it?

**Comment by danitseitlin** [comment]
@davidmfinol I don't have an intel mac to test on. but I did build this project previously on the Apple silicone Mac via the Unity Hub and it works great.
I attempted the permissions and it doens't seem to fix the issue.

**Comment by danitseitlin** [comment]
Also, is this a correct way to specific unity version:
```
- uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: StandaloneOSX
        unityVersion: 2020.3.26f1
        allowDirtyBuild: true

```
