### ISSUE TITLE
WebGL build with disabled compression method.  

### ISSUE THREAD

**Issue by trenner** [game-ci/unity-builder#338]
Hi all,
I'm trying to generate a WebGL build without compression. 

```
- uses: game-ci/unity-builder@v2
  env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  with:
    targetPlatform: WebGL
    customParameters: -UncompressedAssetBundle
```
However, the resulting is always compressed with Brotli. Do you have any idea? Thanks
