### ISSUE TITLE
Keystore & password

### ISSUE THREAD

**Issue by Haelle** [game-ci/unity-builder#34]
Is there a way to pass the keystore file in the parameters ? And also the password ? (using github secrets)

Should it be in the `customParameters` ?

**Comment by webbertakken** [comment]
@Haelle thanks for your request!

I do not know your current context. Could you tell us a bit more about what you are trying to do? Links to official documentation of related tools would be very helpful too. 

Technically you could pass anything in `customParameters` but it depends on the build method what happens to it.

What would be your suggested approach or desired API?

**Comment by Haelle** [comment]
To deploy to the Google PlayStore you need to [sign your application](https://developer.android.com/studio/publish/app-signing).
It's done with a [keystore](https://developer.android.com/training/articles/keystore.html).

In Unity you can then set your keystore in the [Publishing menu](https://docs.unity3d.com/Manual/class-PlayerSettingsAndroid.html#Publishing).

And everytime you want to build your app you need to provide the password of the keystore via the Editor actually.

So for instance via Unity Cloud build you can provide in their web interface the keystore and the password (cannot show sorry). Here is the info in the [FAQ](https://developer.cloud.unity3d.com/support/faq/) section Android, 2rd question

I've never worked with the command line tool, so currently I have no idea how you're doing the command line build... I suppose there is a way to sign the app (as Unity Cloud Build does it !)

**Comment by darkgap** [comment]
Looking at [here](https://github.com/GabLeRoux/unity3d-ci-example#how-to-add-build-targets), the [GabLeRoux](https://github.com/GabLeRoux/unity3d-ci-example#how-to-add-build-targets) unity3d library lets you specify the keystore by binary64  formatting it and putting it in a repos' secret variable

**Comment by dabo248** [comment]
@Haelle did you find a solution for this?

**Comment by webbertakken** [comment]
Feel free to open a PR with your suggested approach. You're free to make any additions to the builder method, as long as it's usable for everyone.

**Comment by Haelle** [comment]
This is in pending on my side, I'll come back to it later

**Comment by webbertakken** [comment]
@Haelle did you work this out? Anything we can reuse for everyone?

**Comment by Haelle** [comment]
No sorry CI is postponed indefinitely for the moment

**Comment by davidmfinol** [comment]
Added these parameters: `androidAppBundle`, `androidKeystoreName`, `androidKeystoreBase64`, `androidKeystorePass`, `androidKeyaliasName`, `androidKeyaliasPass`

I tested with my personal project, but maybe someone else can test with their project to confirm? 
You would pass through GitHub Secrets in your workflow like this: 
```
      - uses: webbertakken/unity-builder@6ece6447b229baedca54df3aae22fc3d097bc4f3
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: builds
          androidAppBundle: true
          androidKeystoreName: keystore.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
```
