### ISSUE TITLE
pro license isn't returned after successful completion on macos-latest

### ISSUE THREAD

**Issue by oshaughnessy** [game-ci/unity-builder#358]
**Bug description**

unity-builder isn't returning a license after successful completion of the build on macos-latest

**How to reproduce**

I'm running builds in a matrix:

```
      - name: Build ${{ matrix.targetPlatform }} Client
        uses: game-ci/unity-builder@main
        env:
          UNITY_EMAIL: ${{ env.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ env.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ env.UNITY_LICENSE }}
          UNITY_SERIAL: ${{ env.UNITY_SERIAL }}
        with:
          buildMethod: MyBuild${{ inputs.build-env }}${{ matrix.targetPlatform }}
          buildName: MyBuild
          customImage: ${{ matrix.customImage }}
          projectPath: .
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ env.UNITY_VERSION }}
```

The `UNITY_` variables are all defined as appropriate, and `UNITY_LICENSE` is empty (this is a generic workflow being called from other workflows).

I only encounter the license problem when `targetPlatform` is `StandaloneOSX`.

`customImage` is defined as `unityci/editor:${{ needs.unity-version.outputs.version }}-mac-mono-0.16`.

**Expected behavior**

The license associated with `UNITY_SERIAL` should no longer be activate when the unity-builder action has completed successfully.

**Additional details**

Log output from the end of the run seems to indicate there may be a problem with something in the API invocation:

```
LICENSE SYSTEM [2022317 21:7:54] Error fetching https://license.unity3d.com/update/poll?cmd=3&tx_id=...
UnityTls interface was not set. Call Curl_unitytls_set_interface first.

LICENSE SYSTEM [2022317 21:8:25] Failed to return license: Unity license return request has timed out. Please verify that you are connected to the Internet and/or try again later.
```

Thank you!
