### ISSUE TITLE
Powershell never exits on Windows and the build hangs forever

### ISSUE THREAD

**Issue by wilg** [game-ci/unity-builder#439]
I don't know if it something with my configuration of a local runner, but something is preventing the Docker container from terminating. I think it is that Powershell never exits after completing the build script, even when explicitly exited. I've been taking some stabs in the dark on my fork, but haven't had any success here. https://github.com/wilg/unity-builder

**Comment by webbertakken** [comment]
Would you mind attaching your workflow file, so we can see your configuration?
Could you also tell us what kind of runner you're using?

**Comment by wilg** [comment]
I'm using local runners, one on Mac, one on Windows. My idea is to have the Mac build Mac IL2CPP and have the Windows machine build Windows IL2CPP and Linux IL2CPP.

The Mac build works properly (though I haven't gotten Steam uploads working yet because of https://github.com/game-ci/steam-deploy/issues/35).

The Windows machine is Windows 11 Pro. I installed Docker via Docker Desktop, maybe that's at issue.

The Windows build fully completes, but the Docker instance hangs. It looks like the Powershell script completes (no code is called after the manual exit I added). However I see that it's possible for Powershell to hang even in this case. https://stackoverflow.com/questions/2041799/powershell-script-gets-stuck-doesnt-exit-when-called-from-batch-file

I have some puzzling configuration issues with memory with docker on Windows, documented here, but manually setting memory/cpu flags got it working. https://github.com/game-ci/unity-builder/issues/432

If I manually terminate the container from Docker Desktop, `docker run` exits (though with a crazy status code of what appears to be INT_MAX) and the build proceeds as normal.


```
name: Build Players
on:
  workflow_dispatch:
    inputs:
      build_mac:
        description: "Build for macOS"
        required: true
        type: boolean
      build_windows:
        description: "Build for Windows"
        required: true
        type: boolean
      build_linux:
        description: "Build for Linux"
        required: true
        type: boolean
env:
  NODE_TLS_REJECT_UNAUTHORIZED: 0
jobs:
  windows_host:
    if: inputs.build_linux || inputs.build_windows
    name: Build for ${{ matrix.platform[1] }} on ${{ matrix.platform[0] }}
    runs-on: [self-hosted, "${{ matrix.platform[0] }}"]
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2021.3.9f1
        platform:
          - [Windows, StandaloneWindows64]
    steps:
      - uses: actions/checkout@v3
        name: Git Checkout + LFS
        with:
          lfs: true
          fetch-depth: 0
          clean: false

      - uses: wilg/unity-builder@main
        name: Build Unity player
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_BUILDER_DOCKER_ARGS: "-m 28g --cpus 10 --gpus all"
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.platform[1] }}
          buildName: Gumshoe
          allowDirtyBuild: true
          # customParameters: "-myParameter myValue -myBoolean -ThirdParameter andItsValue"

      - uses: actions/upload-artifact@v3
        name: Upload builds artifact
        with:
          name: ${{ matrix.platform[1] }}-build
          path: build/${{ matrix.platform[1] }}
          if-no-files-found: error

  mac_host:
    if: inputs.build_mac
    name: Build for ${{ matrix.platform[1] }} on ${{ matrix.platform[0] }}
    runs-on: [self-hosted, "${{ matrix.platform[0] }}"]
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2021.3.9f1
        platform:
          - [macOS, StandaloneOSX]
    steps:
      - uses: actions/checkout@v3
        name: Git Checkout + LFS
        with:
          lfs: true
          fetch-depth: 0
          clean: false

      - uses: wilg/unity-builder@main
        id: build
        name: Build Unity player
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.platform[1] }}
          buildName: Gumshoe
          allowDirtyBuild: true
          # customParameters: "-myParameter myValue -myBoolean -ThirdParameter andItsValue"

      - uses: wilg/steam-deploy@main
        env:
          STEAM_HOME: ~/Library/Application Support/Steam/
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
          ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
          appId: 2154550
          buildDescription: ${{ steps.build.outputs.buildVersion}}
          rootPath: build
          depot2Path: StandaloneOSX
          releaseBranch: beta

      # - name: Zip build
      #   run: |
      #     ditto -c -k --keepParent --sequesterRsrc build/${{ matrix.platform[1] }}/Gumshoe.app build/${{ matrix.platform[1] }}/artifacts/Gumshoe.app.zip

      # - uses: actions/upload-artifact@v3
      #   name: Upload builds artifact
      #   with:
      #     name: ${{ matrix.platform[1] }}-build-zip
      #     path: build/${{ matrix.platform[1] }}/artifacts
      #     if-no-files-found: error
```
