### ISSUE TITLE
How to run player after build on ubuntu

### ISSUE THREAD

**Issue by timcassell** [game-ci/unity-builder#482]
I'm trying to run my player after its built, but I'm getting an error that says `./build/StandaloneLinux64: Is a directory`. I'm not too familiar with ubuntu, so I'm not sure how I can run it.

```yml
- name: Build Project
  uses: game-ci/unity-builder@v2
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_UBUNTU }}
  with:
    projectPath: IL2CPP_Tests
    targetPlatform: StandaloneLinux64

- name: Run Tests
  run: |
    ./build/StandaloneLinux64 -batchmode --result:TestResults/test-results-il2cpp.xml --trace=Info --labels=All
```

Is this possible?

(In case you're wondering why I want to do this, it's because I'm trying to run unit tests on the IL2CPP runtime directly using `NUnitLite`, since unity test runner doesn't work.)
