### ISSUE TITLE
Android symbols not generating

### ISSUE THREAD

**Issue by uchar** [game-ci/unity-builder#513]
**Bug description**

I'm using this script for building android bundle :
```
     - uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          versioning: Custom
          version: ${{ github.event.inputs.buildVersion }}
          targetPlatform: Android
          androidAppBundle: true
          androidSymbolType: public
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          allowDirtyBuild: true
          sshAgent: ${{ env.SSH_AUTH_SOCK }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-Android
          path: build
```
But when I download the output, there is no symbols.zip inside it , 
It seems that it doesn't generate it at all , this is the output log : 
```
###########################
#       Build output      #
###########################

total 92M
drwxr-xr-x 3 root root 4.0K Feb 19 17:20 .
drwxr-xr-x 3 root root 4.0K Feb 19 17:03 ..
-rw-r--r-- 1 root root  92M Feb 19 17:20 Android.aab
drwxr-xr-x 4 root root 4.0K Feb 19 17:20 Android_BackUpThisFolder_ButDontShipItWithYourGame
```

I'm also getting this warning : 
```
Warning: Unexpected input(s) 'androidSymbolType', valid inputs are ['targetPlatform', 'unityVersion', 'customImage', 
'projectPath', 'buildName', 'buildsPath', 'buildMethod', 'customParameters', 'versioning', 'version', 'androidVersionCode', 
'androidAppBundle', 'androidKeystoreName', 'androidKeystoreBase64', 'androidKeystorePass', 'androidKeyaliasName', 
'androidKeyaliasPass', 'androidTargetSdkVersion', 'sshAgent', 'gitPrivateToken', 'chownFilesTo', 'allowDirtyBuild', 'postBuildSteps',
 'preBuildSteps', 'customJobHooks', 'customJob', 'awsBaseStackName', 'cloudRunnerCluster', 'cloudRunnerCpu', 
'cloudRunnerMemory', 'cachePushOverrideCommand', 'cachePullOverrideCommand', 'readInputFromOverrideList', 
'readInputOverrideCommand', 'kubeConfig', 'kubeVolume', 'kubeStorageClass', 'kubeVolumeSize', 'cacheKey', 
'checkDependencyHealthOverride', 'startDependenciesOverride']
```
