### ISSUE TITLE
buildMethod fails on iOS

### ISSUE THREAD

**Issue by sivhjo** [game-ci/unity-builder#530]
**Bug description**

Using buildMethod along with customParameters fails on iOS.
It doesn't seem to be a directly game-ci issue, but something with the docker image.

This is the error that appears:
```
Aborting batchmode due to failure:
executeMethod class 'Foo' could not be found.
Argument was -executeMethod NameSpace.With.Several.Segments.Foo.Bar
```

This _only_ happens with iOS specifically.
The platforms StandaloneWindows64, StandaloneOSX, Android, and WebGL work as intended.
I'm using a matrix strategy, so the workflow job for each platform is exactly the same.

Workflow is using the image `unityci/editor:ubuntu-2021.3.20f1-ios-1`. Unsure if it is just this specific image with the issue, haven't tested with other Editor versions.

Example:
```
      - name: Build asset bundles
        id: build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_BASE_EDITOR_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_BASE_EDITOR_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_BASE_EDITOR_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          gitPrivateToken: ${{ secrets.UNITY_BASE_GITHUB_TOKEN }}
          buildMethod: NameSpace.With.Several.Segments.Foo.Bar
          customParameters: -slackAccessToken ${{ secrets.SLACK_BOT_TOKEN }} -slackChannelId ${{ vars.SLACK_ABB_CHANNEL_ID }}
```

**How to reproduce**

- Create a new workflow that checks out a unity project using actions/checkout@v3
- Unity project needs a namespaced, static editor method to call
- Unity project should be version 2021.3.20f1
- Use target platform iOS
- Call a static editor method with buildMethod
- Run workflow

**Expected behavior**

Unity should find the method and call it.

**Additional details**

The editor method I'm calling is installed as a git dependency (and later will be made into a package).
It's in an Editor folder in an Editor assembly. The assembly definition has Editor as its only platform.
