### ISSUE TITLE
Warning: Unexpected input(s) 'cacheUnityInstallationOnMac'

### ISSUE THREAD

**Issue by mdarvanaghi** [game-ci/unity-builder#541]
**Bug description**
Cannot use input cacheUnityInstallationOnMac. Workflow gives the following error: 'Warning: Unexpected input(s) 'cacheUnityInstallationOnMac''

**How to reproduce**

Run workflow with the following input for the unity-builder:

```
- name: Build project
  uses: game-ci/unity-builder@v2
  with:
    cacheUnityInstallationOnMac: 'true'
```

**Expected behavior**

Workflow would cache the Unity installation for the macos-latest runner to use. 

**Additional information**

This input is described in the [documentation for the Builder](https://game.ci/docs/github/builder/#cacheunityinstallationonmac)
