### ISSUE TITLE
Android Build Fails on Unity 2021.3.20

### ISSUE THREAD

**Issue by felipeViana** [game-ci/unity-builder#547]
**Bug description**

The build on Github Actions always fail on game-ci/unity-builder@v2

**How to reproduce**

Trigger an Android build no Github Actions

**Expected behavior**

Success build

**Additional details**
In the logs indicate that the build has 2 errors and 1 warning but I need help identifying those.
My main guess for the error is this part:
```
Your mono runtime and class libraries are out of sync.
The out of sync library is: /opt/unity/Editor/Data/MonoBleedingEdge/lib/mono/unityjit-linux/System.dll
```

I couldn't post full log because it's too long for this, so I'll post other parts that seems to point to errors:
```
WorkingDir: /github/workspace
ExitCode: 4 Duration: 0s38ms
[             ] Require frontend run.  Library/Bee/1300b0aE.dag couldn't be loaded
Starting: /opt/unity/Editor/Data/Tools/netcorerun/netcorerun "/opt/unity/Editor/Data/Tools/BuildPipeline/ScriptCompilationBuildProgram.exe" "Library/Bee/1300b0aE.dag.json" "Library/Bee/1300b0aE-inputdata.json" "Library/Bee/buildprogram0.traceevents"
```

`[Licensing::Module] Error: Access token is unavailable; failed to update`

```
UnityException: Can not sign the application
Unable to sign the application; please provide passwords!
```

My config file:
```
name: Build project

on: [push]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        targetPlatform:
          - Android # Build an Android .apk standalone app.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic

      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

```
