### ISSUE TITLE
unknown option when building unity project for webgl on aws cloudrunner

### ISSUE THREAD

**Issue by dev-rsh** [game-ci/unity-builder#560]
Hello
I am using unity-builder to build my unity project for webgl target platform. 
Currently I am encountering problems with the build itself. The build outputs the following error 

`Error: error: unknown option '--logFile'`

I'm following the official documentation and the configuration that I'm using in my workflow is as following:

```
      - uses: game-ci/unity-builder@cloud-runner-develop
        id: aws-fargate-unity-build
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}        
        with:
          providerStrategy: aws
          targetPlatform: WebGL
          gitPrivateToken: ${{ secrets.GH_TOKEN }}
          containerCpu: 4096
          containerMemory: 8192
```

Is there any problem with my configuration? any help would be greatly appreciated! Thanks!
