### ISSUE TITLE
Cannot use custom docker image

### ISSUE THREAD

**Issue by OudomMunint** [game-ci/unity-builder#562]
**Bug description**

Error response from daemon: pull access denied for unityci/editor-ubuntu-2023.1.9f1-windows-mono-2.0.0)

**Additional details**

My workflow code:

``` yml
on:
  push:
    branches:
      - master
      
permissions:
  contents: write
  
jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        targetPlatform:
          - StandaloneWindows
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          customImage: 'unityci/editor-ubuntu-2023.1.9f1-windows-mono-2.0.0'

      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
```
