### ISSUE TITLE
Unclassified error occured while trying to activate license

### ISSUE THREAD

**Issue by SeoulSKY** [game-ci/unity-builder#565]
**Bug description**

It throws an error even though I followed [this document](https://game.ci/docs/github/activation#personal-license) for the activation:
```
---------- git config --list --show-origin -------------
file:/etc/gitconfig	filter.lfs.required=true
file:/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:/etc/gitconfig	filter.lfs.process=git-lfs filter-process
Changing to "/github/workspace/_activate-license~" directory.
/github/workspace/_activate-license~ /github/workspace
Requesting activation (personal license)
Unclassified error occured while trying to activate license.
Exit code was: 1
Error: The process '/usr/bin/docker' failed with exit code 1
```

**How to reproduce**

Run this workflow:
```yml
    - name: Build Unity project
      uses: game-ci/unity-builder@v3
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: WebGL
        unityVersion: 2022.3.7f1
        projectPath: /path/to/project
```

**Expected behavior**

Successfully built the Unity project

**Additional details**

* I used a personal license.
* My password for the Unity account only contains alphabets and numbers (no special characters such as ! and #)
