### ISSUE TITLE
Workflow failing for android even after getting "Build Succeeded" 

### ISSUE THREAD

**Issue by Lokhandwalah** [game-ci/unity-builder#567]
**Bug description**

When I am trying to build unity for android platform, the build is successful but I still get the error and the workflow fails
I am using this in my current workflow

```
      - name: Build Unity
        uses: game-ci/unity-builder@v3
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_USERNAME }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_PRO_SERIAL_KEY }}
        with:
          targetPlatform: Android
          projectPath: ./andromeda
          buildMethod: UnityBuilderAction.Build.DoBuildAndroidLibrary
          customImage: unityci/editor:ubuntu-2020.3.42f1-android-2
```

I can see this in the logs

```
Exiting batchmode successfully now!
Build succeeded

###########################
#       Build output      #
###########################
```

but this is what I get at the end

```
LICENSE SYSTEM [2023830 19:4:12] Received https://activation.unity3d.com/license.fcgi?CMD=3&TX=1696faac5bc1bc7a082b5da8501de02f&RX=GEN-7b86ec0d-4fa0-48c6-ab01-0d706921b358

LICENSE SYSTEM [2023830 19:4:12] Headers:
    HTTP/1.1 200 OK
    Cache-Control: no-cache, no-store, must-revalidate
    Pragma: no-cache
    Expires: 0
    Vary: Accept-Encoding
    Content-Encoding: deflate
    sc-request-id: 2706fd13-79c1-495b-a772-b525f74e6ee4
    Content-Type: text/xml
    Content-Length: 1132
    
LICENSE SYSTEM [2023830 19:4:12] Information: Unity license returned.
/github/workspace
Error: There was an error building the project. Please read the logs for details.
```

You can see the full logs [here](https://drive.google.com/file/d/11JIEt8-C90TUhpnXPhRiD6KlZ7iIQMNR/view?usp=sharing)

**Expected behavior**

I should be able to move forward in my workflow

**Additional details**
