### ISSUE TITLE
Error: There was an error building the project. Please read the logs for details

### ISSUE THREAD

**Issue by humbertodias** [game-ci/unity-builder#584]
**Bug description**

After successfully build on the license step fails saying  "Error: There was an error building the project. Please read the logs for details."

**How to reproduce**

1. Configure the step

```yaml
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
```
2. Setup the secret variable UNITY_LICENSE
3. Launch the build action manually
4. Linux/Mac/Windws build will fail

Step configured
https://github.com/humbertodias/unity-mugen/blob/main/.github/workflows/release.yml

**Expected behavior**

Should pass through without any problem, because the activation was completed. 
```
Changing to "/github/workspace/_activate-license~" directory.
/github/workspace/_activate-license~ /github/workspace
Requesting activation (personal license)
Activation complete.
```
Another weird behavior is related to WebGL version that works well
![image](https://github.com/game-ci/unity-builder/assets/9255997/f34fee38-e120-4339-aaf4-ee5111af50ca)
However, linux, windows and mac fails.

**Additional details**

Log
https://github.com/humbertodias/unity-mugen/actions/runs/6508708719/job/17680421661
```
Build succeeded

###########################
#       Build output      #
###########################

total 32M
drwxr-xr-x 4 root root 4.0K Oct 13 14:04 .
drwxr-xr-x 3 root root 4.0K Oct 13 13:50 ..
-rwxr-xr-x 1 1000 1000  15K Oct 13 14:04 StandaloneLinux64
drwxr-xr-x 3 root root 4.0K Oct 13 14:04 StandaloneLinux64_BurstDebugInformation_DoNotShip
drwxr-xr-x 7 root root 4.0K Oct 13 14:04 StandaloneLinux64_Data
-rwxr-xr-x 1 1000 1000  32M Oct 13 14:04 UnityPlayer.so
Changing to "/github/workspace/_activate-license~" directory.
/github/workspace/_activate-license~ /github/workspace
/github/workspace
Error: There was an error building the project. Please read the logs for details.
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Build project
```

![image](https://github.com/game-ci/unity-builder/assets/9255997/2cfb4cc8-ce60-46bf-bdd2-28fb8f29d306)
