### ISSUE TITLE
Symbolically linked Library fails on unity-builder@v4

### ISSUE THREAD

**Issue by DenverGylee** [game-ci/unity-builder#603]
**Bug description**

This is on a self-hosted runner. I have a fairly large project that can not use GitHub's cache for my project's Library folder between builds. I wrote a script to symbolically link my Library folder to an auto-generated folder at `~/.cache/PROJECT_NAME/Library`. 

The unity-builder step currently fails if I use a symbolically referenced folder. My current workaround is to `rsync` back and forth my Library folder with the `~/.cache/PROJECT_NAME/Library` but this adds a signficant overhead to my pipeline runtimes.

**How to reproduce**

1. After a successful Library build, move the folder to `~/.cache/PROJECT_NAME/Library`. 
```mv ./PROJECT_NAME/Library ~/.cache/PROJECT_NAME/Library```
2. Create a symbolic link between the paths.
```ln -s ~/.cache/PROJECT_NAME/Library ./PROJECT_NAME/Library```
3. Run the `unity-builder@v4` action in the project. Here is a reference to my actions.
```
- name: Build for Windows
        id: build-for-windows
        uses: game-ci/unity-builder@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: PROJECT_NAME
          allowDirtyBuild: true
          versioning: Semantic
          targetPlatform: StandaloneWindows
          sshAgent: ${{ env.SSH_AUTH_SOCK }}
          runAsHostUser: true
```

**Expected behavior**

Builds would complete as expected rather than utilizing `rsync` back and forth.
