### ISSUE TITLE
Failed to run "git fetch"

### ISSUE THREAD

**Issue by asbjornu** [game-ci/unity-builder#622]
**Bug description**

As mentioned in https://github.com/game-ci/unity-builder/issues/564#issuecomment-1892023344, I'm experiencing the following problem when trying to build my Unity project with `game-ci/unity-builder@v4`:

```
Warning: Fetch --unshallow caught: Error: Failed to run "git fetch --unshallow".
 In-command error caught: Error: The process '/usr/bin/git' failed with exit code 128
Error: Failed to run "git fetch".
 In-command error caught: Error: The process '/usr/bin/git' failed with exit code 128
```

**How to reproduce**

I'm not sure how to reproduce this, but this is a WebGL build if that matters.

**Expected behavior**

`game-ci/unity-builder` shouldn't fail to run `git fetch`. I wonder why it is running `git fetch` at all. Can anyone please provide details as to why it is and possibly how to avoid it?

**Additional information**

The GitHub action configuration looks like the following:

```yaml
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          allowDirtyBuild: true
          targetPlatform: WebGL
          versioning: Semantic
```
