### ISSUE TITLE
Building on self-hosted Windows 11: dockerWorkspacePath doesn't update --workdir

### ISSUE THREAD

**Issue by ah1053** [game-ci/unity-builder#643]
**Bug description**
Running Unity Builder on Windows 11 self-hosted results in this error `docker: Error response from daemon: the working directory 'c:/github/workspace' is invalid, it needs to be an absolute path.` 

Passing in dockerWorkspacePath as prompted doesn't seem to have an effect

Any help is appreciated

**How to reproduce**

- Setup a self-hosted runner on Windows 11 and run unity builder with default args but 

```
game-ci/unity-builder@v4
  with:
    targetPlatform: Android
    dockerWorkspacePath: /github/workspace
    unityVersion: auto
    versioning: Semantic
    androidExportType: androidPackage
    androidSymbolType: none
    runAsHostUser: false
    dockerIsolationMode: default
    containerRegistryRepository: unityci/editor
    containerRegistryImageVersion: [3](https://github.com/storyup/healium-xr-oculus-new/actions/runs/8528284125/job/23361561125#step:4:3)
    awsStackName: game-ci
    providerStrategy: local
    kubeVolumeSize: [5](https://github.com/storyup/healium-xr-oculus-new/actions/runs/8528284125/job/23361561125#step:4:5)Gi
    watchToEnd: true
    cacheUnityInstallationOnMac: false
    skipActivation: false
  env:
    UNITY_SERIAL: ***
    UNITY_EMAIL: ***
    UNITY_PASSWORD: ***
   ```

**Expected behavior**

Adding dockerWorkspacePath will override the `--workdir` however it doesn't

```
"C:\Program Files\Docker\Docker\resources\bin\docker.exe" run 
--workdir c:/github/workspace --rm 
--env UNITY_EMAIL=*** --env UNITY_PASSWORD=*** 
--env UNITY_SERIAL=*** --env SKIP_ACTIVATION=false --env UNITY_VERSION=2021.3.4f1 --env PROJECT_PATH=. --env BUILD_TARGET=Android --env BUILD_NAME=Android --env BUILD_PATH=build/Android --env BUILD_FILE=Android.apk --env MANUAL_EXIT=false --env ENABLE_GPU=false --env VERSION=3.0.1 --env ANDROID_VERSION_CODE=3000001 --env ANDROID_EXPORT_TYPE=androidPackage --env ANDROID_SYMBOL_TYPE=none --env RUN_AS_HOST_USER=false --env GITHUB_REF=refs/heads/test-action --env GITHUB_SHA=056aca9a99267e9142cd9f59ec0d4fc1a6b6e2e5 --env GITHUB_REPOSITORY=storyup/healium-xr-oculus-new --env GITHUB_ACTOR=ah1053 --env "GITHUB_WORKFLOW=Build project" --env GITHUB_EVENT_NAME=push --env GITHUB_ACTION=__game-ci_unity-builder --env GITHUB_EVENT_PATH=C:\Users\ahmed\actions-runner\_work\_temp\_github_workflow\event.json --env RUNNER_OS=Windows --env RUNNER_TOOL_CACHE=C:\Users\ahmed\actions
```
**Additional details**
