### ISSUE TITLE
Im Try to follow  gameCI doc and got some fail build.

### ISSUE THREAD

**Issue by unitodev** [game-ci/unity-builder#645]
**Bug description**
unity 2022.3.8f1 version

**How to reproduce**
this is my yml
```
`name: Actions 😎

on: 
  push:
    branches:
      - TestCI(demo)
jobs:
  build:
    name: Build my project ✨
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v4

#      # Git LFS
#      - name: Create LFS file list
#        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
#
#      - name: Restore LFS cache
#        uses: actions/cache@v3
#        id: lfs-cache
#        with:
#          path: .git/lfs
#          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
#
#      - name: Git LFS Pull
#        run: |
#          git lfs pull
#          git add .
#          git reset --hard

      # Cache
      - uses: actions/cache@v4.0.2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
           Library-MyProjectName-
           Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4.2.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          versioning: Semantic
          allowDirtyBuild: true
          targetPlatform: WebGL
          

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build`

```

-

**Expected behavior**

**Additional details**

![image](https://github.com/game-ci/unity-builder/assets/118905626/73a9d892-be04-47c3-abdf-b6422ca0934a)
