### ISSUE TITLE
Windows IL2CPP build failing to activate intermittently

### ISSUE THREAD

**Issue by davidmfinol** [game-ci/unity-builder#651]
**Bug description**

Trying to build with Windows IL2CPP for Unity 2022.3.x.
I am intermittently getting this error during the activate step:
```
User *** logged in successfully
[UnityConnect::TryLogin] Request Succeeded.
[Licensing::Module] Trying to connect to existing licensing client channel...
[Licensing::IpcConnector] Connection attempt to the License Client on channel: "LicenseClient-ContainerAdministrator" failed because channel doesn't exist; code: "0x80000002"
[Licensing::Module] Successfully launched the LicensingClient (PId: 6364)
[Licensing::IpcConnector] Connection attempt to the License Client on channel: "LicenseClient-ContainerAdministrator" failed because channel doesn't exist; code: "0x80000002"
[Licensing::Module] Timed-out after 5.01s, waiting for channel: "LicenseClient-ContainerAdministrator"
IPC channel to LicensingClient doesn't exist; aborting
Exiting without the bug reporter. Application will terminate with return code 199Activation failed, with exit code 199
```

**How to reproduce**

- Use this workflow: https://github.com/finol-digital/Card-Game-Simulator/actions/runs/9119802902/workflow
- Specifically this job:
```
  buildWithWindows:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: windows-2022
    needs: [buildWithLinux, buildWithMac]
    outputs:
      buildVersion: ${{ steps.buildStep.outputs.buildVersion }}
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows
          - StandaloneWindows64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-buildWindows-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-buildWindows-${{ matrix.targetPlatform }}-
            Library-buildWindows-
      - name: Build Unity Project
        id: buildStep
        timeout-minutes: 45
        uses: game-ci/unity-builder@main
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL_PERSONAL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD_PERSONAL }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL_PERSONAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: Cgs.Editor.BuildCgs.BuildOptions
      - name: Upload Build
        uses: actions/upload-artifact@v4
        if: github.event.action == 'published' || contains(github.event.inputs.workflow_mode, matrix.targetPlatform) || (contains(github.event.inputs.workflow_mode, 'Steam') && contains(matrix.targetPlatform, 'StandaloneWindows'))
        with:
          path: build/${{ matrix.targetPlatform }}
          name: cgs-${{ matrix.targetPlatform }}
      - name: Zip Build
        uses: vimtor/action-zip@v1.2
        if: github.event.action == 'published' && matrix.targetPlatform != 'WSAPlayer'
        with:
          files: build/${{ matrix.targetPlatform }}/
          dest: cgs-${{ matrix.targetPlatform }}.zip
      - name: Upload Zip to GitHub Release
        uses: svenstaro/upload-release-action@v2
        if: github.event.action == 'published' && matrix.targetPlatform != 'WSAPlayer'
        with:
          repo_token: ${{ secrets.CGS_PAT }}
          asset_name: cgs-${{ matrix.targetPlatform }}.zip
          file: cgs-${{ matrix.targetPlatform }}.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: ${{ github.event.release.body }}
```

**Expected behavior**

Build should succeed.

**Additional details**

https://github.com/game-ci/unity-builder/issues/569 may be related.
