### ISSUE TITLE
Error: Cannot build untitled scene.

### ISSUE THREAD

**Issue by CorbyO** [game-ci/unity-builder#658]
**Bug description**

Failed build with "Cannot build untitled scene." message when "Scenes In Build" has scenes.
![image](https://github.com/user-attachments/assets/5ad11d4d-d7f8-43ae-bac5-a4eb9ed4dd3c)
![image](https://github.com/user-attachments/assets/45ee01f0-6d06-492b-924d-c33f2ac6507d)

I've already checked these:
https://github.com/game-ci/docker/issues/196
https://github.com/game-ci/unity-request-activation-file/issues/85

**How to reproduce**

```yml
# .github/workflows/test-unity.yml
name: Test Unity

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          path: ***

      - name: Unity Build Android
        uses: ./.github/actions/unity-build
        with:
          unity_license: ${{ secrets.UNITY_LICENSE }}
          unity_email: ${{ secrets.UNITY_EMAIL }}
          unity_password: ${{ secrets.UNITY_PASSWORD }}
          android_keystore_base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          android_keystore_password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          android_key_alias_name: ${{ secrets.ANDROID_KEY_ALIAS_NAME }}
          android_key_alias_password: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
          project_path: ***
      
      - uses: actions/upload-artifact@v3
        with:
          name: ***
          path: build

```

```yml
# .github/actions/unity-build/action.yml
name: 'Unity Build Android'
description: 'Builds a Unity project for Android'
inputs:
  unity_license:
    description: 'Unity License'
    required: true
  unity_email:
    description: 'Unity Email'
    required: true
  unity_password:
    description: 'Unity Password'
    required: true
  android_keystore_base64:
    description: 'Android KeyStore Base64'
    required: true
  android_keystore_password:
    description: 'Android KeyStore Password'
    required: true
  android_key_alias_name:
    description: 'Android Key Alias Name'
    required: true
  android_key_alias_password:
    description: 'Android Key Alias Password'
    required: true
  project_path:
    description: 'Path to the Unity project'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install -g bats
      shell: bash
    - run: bats -v
      shell: bash

    - name: Calculate Cache Key
      id: cache-key
      run: echo "CACHE_KEY=Library-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      shell: bash

    - name: Cache Library
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-

    - name: Build project
      uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ inputs.unity_license }}
        UNITY_EMAIL: ${{ inputs.unity_email }}
        UNITY_PASSWORD: ${{ inputs.unity_password }}
      with:
        runAsHostUser: true
        enableGpu: true
        projectPath: ${{ inputs.project_path }}
        unityVersion: 2022.3.37f1
        buildName: BlobSurviveCI
        customParameters: '-nographics'
        allowDirtyBuild: true
        targetPlatform: Android
        androidExportType: androidAppBundle
        androidKeystoreName: ***.keystore
        androidKeystoreBase64: ${{ inputs.android_keystore_base64 }}
        androidKeystorePass: ${{ inputs.android_keystore_password }}
        androidKeyaliasName: ${{ inputs.android_key_alias_name }}
        androidKeyaliasPass: ${{ inputs.android_key_alias_password }}
        # buildMethod: UnityBuilderAction.BuildScriptForDevelopment.Build

```

-

**Additional details**

Problem logs:
```
Warning: 
      Library folder does not exist.
      Consider setting up caching to speed up your workflow,
      if this is not your first build.
.
.
.
[             ] Require frontend run.  Library/Bee/1300b0aP.dag couldn't be loaded
.
.
.
Cannot build untitled scene.
.
.
.
Error: Build failed with exit code 103
```
