### ISSUE TITLE
UPM authentication and runAsHostUser on self-hosted linux runner

### ISSUE THREAD

**Issue by eberleinNeobird** [game-ci/unity-builder#660]
**Bug description**

I created a self-hosted linux runner für github, to build my unity app. When i set the unity-builder runAsHosteUser to true authentication to UPM Server fails:
```
An error occurred while resolving packages:
  Project has invalid dependencies:
    com.neobird.bootstrap: Request [GET <my verdaccio package>] failed because it lacks valid authentication credentials
```

**How to reproduce**

Install linux runner like descriped on: 
https://game.ci/docs/self-hosting/host-provisioning/ubuntu-setup
Use these two steps:
`      - name: Setup UPM Authentication
        timeout-minutes: 10
        run: |
          mkdir ${{ runner.temp }}/_github_home
          cd ${{ runner.temp }}/_github_home
          echo "[npmAuth.\"my verdaccio url"]" >> .upmconfig.toml
          echo "alwaysAuth = true" >> .upmconfig.toml
          echo "token = \"${{ secrets.NPM_AUTH_TOKEN }}\"" >> .upmconfig.toml`

-
and
`      - name: Unity Build (${{ matrix.targetPlatform }}, ${{ matrix.buildProfile }}, ${{ matrix.unityVersion }})
        uses: game-ci/unity-builder@v4
        timeout-minutes: 60
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          runAsHostUser: ${{ matrix.runAsHostUser }}
          versioning: Semantic
          dockerWorkspacePath: /github/workspace
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: NeoBird.Build.BuildScript
          customParameters: '-buildProfile ${{ matrix.buildProfile }`

matrix.runAsHostUser of course is true.

**Expected behavior**

UPM packages should be reloved.

Maybe it's because of step Setup, UPM Authentication does not run as HostUser.
Thx for your help.

**Comment by GabLeRoux** [comment]
Here is something you might try to resolve your authentication issue with UPM. (Note: I did not try this).

When using `runAsHostUser: true` on a self-hosted Linux runner, the problem might be from the `.upmconfig.toml` file not being accessible or correctly configured for the host user.

1. **Adjust UPM Authentication Setup:**
   Place the `.upmconfig.toml` in the host user's home directory:

   ```yaml
   - name: Setup UPM Authentication
     timeout-minutes: 10
     run: |
       mkdir -p $HOME/.upmconfig
       echo "[npmAuth.\"<your verdaccio url>\"]" >> $HOME/.upmconfig/.upmconfig.toml
       echo "alwaysAuth = true" >> $HOME/.upmconfig/.upmconfig.toml
       echo "token = \"${{ secrets.NPM_AUTH_TOKEN }}\"" >> $HOME/.upmconfig/.upmconfig.toml
   ```

2. **Ensure Permissions:**
   Ensure the file has the correct permissions for the host user:

   ```yaml
   - name: Set Permissions for UPM Config
     run: |
       chown -R $(whoami) $HOME/.upmconfig
   ```

3. **Use the Correct User:**
   Ensure the Unity build step runs as the correct user:

   ```yaml
   - name: Unity Build
     uses: game-ci/unity-builder@v4
     timeout-minutes: 60
     env:
       UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
       UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
       UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
     with:
       runAsHostUser: true
       versioning: Semantic
       dockerWorkspacePath: /github/workspace
       unityVersion: ${{ matrix.unityVersion }}
       targetPlatform: ${{ matrix.targetPlatform }}
       buildMethod: NeoBird.Build.BuildScript
       customParameters: '-buildProfile ${{ matrix.buildProfile }}'
   ```

The UPM configuration file is documented here: https://docs.unity3d.com/Manual/upm-config.html
