### ISSUE TITLE
Unity Path Error on self-hosted Windows Runner

### ISSUE THREAD

**Issue by DavidJakszta** [game-ci/unity-builder#663]
**Bug description**

When building with game-ci/unity-builder@v4 and containerRegistryImageVersion: 2 the Unity Path isn't found.
The Unity Path either doesn't seem to be correct or something failed in the pulling/creating of the container. Also the action doesn't fail but that is of less concern to me at the moment.
![image](https://github.com/user-attachments/assets/72e6cacb-cdc4-40c0-9cb7-87198c778907)

**How to reproduce**

- Use unity-builder action in workflow on a self-hosted windows 10, with container RegistryImageVersion: 2 specified.
- Docker-Image: unityci/editor:windows-2021.3.22f1-windows-il2cpp-2
- Workflow yaml:
```
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows
          buildMethod: BuildScript.PerformWindowsBuild${{ inputs.build-method }}
          #runAsHostUser: true
          dockerWorkspacePath: /github/workspace
          containerRegistryImageVersion: 2
```
**Expected behavior**

- The Unity installation is found and the license is activated succesfully.
**Additional details**
Rather a question: is it possible to ssh into the container or something to see what could be wrong with the path?
