### ISSUE TITLE
Build failed with "The process '/bin/bash' failed with exit code 1" on self-hosted MacOS

### ISSUE THREAD

**Issue by Knight52** [game-ci/unity-builder#700]
Hi, I'm trying to build on MacOS so that in the end I can build an iOS app and directly deploy to the app store, but I ran into this problem that it just says the build failed with exit code 1 on /bin/bash with very little information to go on.

```
Run game-ci/unity-builder@v4
  with:
    targetPlatform: StandaloneWindows
    unityVersion: auto
    versioning: Semantic
    androidExportType: androidPackage
    androidSymbolType: none
    runAsHostUser: false
    dockerIsolationMode: default
    containerRegistryRepository: unityci/editor
    containerRegistryImageVersion: 3
    awsStackName: game-ci
    providerStrategy: local
    kubeVolumeSize: 5Gi
    watchToEnd: true
    cacheUnityInstallationOnMac: false
    dockerWorkspacePath: /github/workspace
    skipActivation: false
  env:
    UNITY_LICENSE: ***
    UNITY_EMAIL: ***
    UNITY_PASSWORD: ***
Warning: 
      Library folder does not exist.
      Consider setting up caching to speed up your workflow,
      if this is not your first build.
    
/bin/sh
       0
       0

Generated version 0.0.104 (no version tags found).
Using android versionCode 104
Building locally
Error: The process '/bin/bash' failed with exit code 1
```

Here's the yaml file:

```
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      
      #- name: Run tests
      #  uses: game-ci/unity-test-runner@v4
      #  env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #  with:
      #    githubToken: ${{ secrets.TOKEN }}
      
      - name: Build project
        uses: game-ci/unity-builder@v4
        env: 
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows

      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: Build
```

I would love to debug more though, so even if you suggest me how to continue debugging this, I'm all ears.
