### ISSUE TITLE
Unity 6.1 not supported for build

### ISSUE THREAD

**Issue by IAFahim** [game-ci/unity-builder#704]
**Unity 6.1 not supported for build**

**Steps to reproduce**

``` yaml 
name: Build-And-Release-Android-Main

# Trigger on pushes to the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

# Define a base version - UPDATE THIS AS YOUR MAIN VERSION CHANGES
env:
  BASE_VERSION: "0.1.0" # <-- IMPORTANT: Set your starting base version here

jobs:
  buildAndroid:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
           tool-cache: false
           android: true
           dotnet: true
           haskell: true
           large-packages: false
           swap-storage: false

      - name: Build Unity Project (Android)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          # Optional: Specify build options if needed
          # androidAppBundle: true # Set true for .aab
          # buildName: YourGameName # Set if needed

      - name: Upload Android Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-Android # Consistent artifact name
          path: build/Android # Upload the build output directory

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: buildAndroid # Run only after buildAndroid succeeds
    # --- Add this permissions block ---
    permissions:
      contents: write # Allow creating releases and uploading artifacts
    # ----------------------------------
    steps:
      - name: Download Android Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-Android # Must match the upload name
          path: build/Android # Download to this path

      - name: Calculate Version Tag
        id: calculate_version
        run: |
          VERSION_TAG="v${{ env.BASE_VERSION }}-build.${{ github.run_number }}"
          echo "Calculated tag: $VERSION_TAG"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
      # Check artifact paths are correct for your build output
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/Android/*.apk
            build/Android/*.aab
          # Or specify exact names:
          # artifacts: build/Android/YourGameName.apk,build/Android/YourGameName.aab
          tag: ${{ env.VERSION_TAG }}
          name: "Build ${{ github.run_number }} (${{ env.VERSION_TAG }})"
          body: "Automated build for commit ${{ github.sha }} on main branch."
          token: ${{ secrets.GITHUB_TOKEN }} # Continue using the standard token
          prerelease: true
          makeLatest: false
          allowUpdates: false
```

**Expected behavior**

It should have start building

**Additional details**

```yaml 
Run game-ci/unity-builder@v4
  with:
    targetPlatform: Android
    unityVersion: auto
    versioning: Semantic
    androidExportType: androidPackage
    androidSymbolType: none
    runAsHostUser: false
    dockerIsolationMode: default
    containerRegistryRepository: unityci/editor
    containerRegistryImageVersion: 3
    awsStackName: game-ci
    providerStrategy: local
    kubeVolumeSize: 5Gi
    watchToEnd: true
    cacheUnityInstallationOnMac: false
    dockerWorkspacePath: /github/workspace
    skipActivation: false
  env:
    BASE_VERSION: 0.1.0
    UNITY_LICENSE: ***
    UNITY_EMAIL: ***
    UNITY_PASSWORD: ***
Warning: 
      Library folder does not exist.
      Consider setting up caching to speed up your workflow,
      if this is not your first build.
    
/usr/bin/sh
2
2

Found semantic version 0.0.1 for main@ad111b5
Using android versionCode 1
Building locally
/usr/bin/docker run --workdir /github/workspace --rm --env UNITY_EMAIL=*** --env UNITY_PASSWORD=*** --env UNITY_SERIAL=*** --env SKIP_ACTIVATION=false --env UNITY_VERSION=6000.1.0f1 --env PROJECT_PATH=. --env BUILD_TARGET=Android --env BUILD_NAME=Android --env BUILD_PATH=build/Android --env BUILD_FILE=Android.apk --env MANUAL_EXIT=false --env ENABLE_GPU=false --env VERSION=0.0.1 --env ANDROID_VERSION_CODE=1 --env ANDROID_EXPORT_TYPE=androidPackage --env ANDROID_SYMBOL_TYPE=none --env RUN_AS_HOST_USER=false --env GITHUB_REF=refs/heads/main --env GITHUB_SHA=ad111b55a91e8fdaa725186b3b54d4bf64251d8a --env GITHUB_REPOSITORY=IAFahim/Metro-Hustle --env GITHUB_ACTOR=IAFahim --env GITHUB_WORKFLOW=Build-And-Release-Android-Main --env GITHUB_EVENT_NAME=push --env GITHUB_ACTION=__game-ci_unity-builder --env GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json --env RUNNER_OS=Linux --env RUNNER_TOOL_CACHE=/opt/hostedtoolcache --env RUNNER_TEMP=/home/runner/work/_temp --env RUNNER_WORKSPACE=/home/runner/work/Metro-Hustle --env GITHUB_WORKSPACE=/github/workspace --env GIT_CONFIG_EXTENSIONS --volume /home/runner/work/_temp/_github_home:/root:z --volume /home/runner/work/_temp/_github_workflow:/github/workflow:z --volume /home/runner/work/Metro-Hustle/Metro-Hustle:/github/workspace:z --volume /home/runner/work/_actions/game-ci/unity-builder/v4/dist/default-build-script:/UnityBuilderAction:z --volume /home/runner/work/_actions/game-ci/unity-builder/v4/dist/platforms/ubuntu/steps:/steps:z --volume /home/runner/work/_actions/game-ci/unity-builder/v4/dist/platforms/ubuntu/entrypoint.sh:/entrypoint.sh:z --volume /home/runner/work/_actions/game-ci/unity-builder/v4/dist/unity-config:/usr/share/unity3d/config/:z --volume /home/runner/work/_actions/game-ci/unity-builder/v4/dist/BlankProject:/BlankProject:z --cpus=4 --memory=15190m unityci/editor:ubuntu-6000.1.0f1-android-3 /bin/bash -c /entrypoint.sh
Unable to find image 'unityci/editor:ubuntu-6000.1.0f1-android-3' locally
docker: Error response from daemon: manifest for unityci/editor:ubuntu-6000.1.0f1-android-3 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
Error: Build failed with exit code 125
```
